version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "5672" ]
        interval: 30s
        timeout: 10s
        retries: 5
#  worker:
#    build: .
#    hostname: worker
#    entrypoint: celery
#    command: -A app worker --loglevel=info
#    user: nobody
#    restart: on-failure
#    depends_on:
#      - rabbitmq
#  rate_limiter_1:
#    build: .
#    ports:
#      - "8080:5000"
#  rate_limiter_2:
#    build: .
#    ports:
#      - "8081:5000"
#  rate_limiter_3:
#    build: .
#    ports:
#      - "8082:5000"