version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
#  rate_limiter_1:
#    build: .
#    ports:
#      - "8080:5000"
#  rate_limiter_2:
#    build: .
#    ports:
#      - "8081:5000"
#  rate_limiter_3:
#    build: .
#    ports:
#      - "8082:5000"